DROP DATABASE IF EXISTS LoteriaPrimitiva;
CREATE DATABASE IF NOT EXISTS LoteriaPrimitiva;

USE LoteriaPrimitiva;

DROP TABLE IF EXISTS LoteriaPrimitiva;
CREATE TABLE IF NOT EXISTS Sorteos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    num1 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num2 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num3 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num4 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num5 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num6 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    complementario TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    reintegro TINYINT UNSIGNED CHECK (reintegro BETWEEN 0 AND 9)
);

DROP TABLE IF EXISTS boletos;
CREATE TABLE IF NOT EXISTS boletos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sorteo_id INT UNSIGNED,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    num1 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num2 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num3 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num4 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num5 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    num6 TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    complementario TINYINT UNSIGNED CHECK (reintegro BETWEEN 1 AND 49),
    reintegro TINYINT UNSIGNED CHECK (reintegro BETWEEN 0 AND 9),
    FOREIGN KEY (sorteo_id)
        REFERENCES Sorteos (id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO Sorteos VALUES (1, DEFAULT, 10, 24, 25, 31, 32, 36, 48, 9);

INSERT INTO Boletos VALUES
(1, 1, DEFAULT, 5, 7, 9, 10, 30, 31, 23, 9), 
(2, 1, DEFAULT, 10, 24, 25, 31, 30, 36, 48, 9);
